<?php

/**
 * @file
 * Provides a dispatcher for batch processing service.
 */

/**
 * Batch callback to dispatch the entity batch operation to a service.
 */
function _add_translation_batch_dispatcher() {
  $args = func_get_args();
  list($service, $method) = explode(':', array_shift($args));
  $values = $args[1];
  $args[1] = &$values;
  call_user_func_array([\Drupal::service($service), $method], $args);
}
